name: Build Windows EXE

on:
  release:
    types: [published, edited, created]

jobs:
  build:
    runs-on: windows-latest
    # WICHTIG: Hier geben wir dem Workflow explizit Schreibrechte!
    permissions:
      contents: write

    env:
      # Fix für die Node.js 24 Warnung
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install customtkinter pyinstaller

    - name: Build with PyInstaller
      shell: pwsh
      run: |
        $tk_path = python -c "import customtkinter; import os; print(os.path.dirname(customtkinter.__file__))"
        
        pyinstaller --noconsole --onefile --name "MediaFixer-windows" `
        --add-data "locales;locales" `
        --add-data "audio_flags.json;." `
        --add-data "$($tk_path);customtkinter" `
        main.py

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v2
      with:
        files: dist/MediaFixer-windows.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}