name: Build Multi-OS Binaries

on:
  release:
    types: [published, edited, created]

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      matrix:
        include:
          - os: windows-latest
            artifact_name: "MediaFixer-windows"
            pyinstaller_mode: "--onedir"
            sep: ";"
          - os: ubuntu-latest
            artifact_name: "MediaFixer-linux"
            pyinstaller_mode: "--onefile"
            sep: ":"

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sv-ttk pyinstaller pymediainfo

      - name: Inject Version and Set Env
      shell: bash
      run: |
        # Version holen und evtl. v entfernen
        TAG_NAME="${{ github.event.release.tag_name }}"
        CLEAN_VERSION=${TAG_NAME#v}
        
        # APP_VERSION überschreiben (fehlertolerant bei Leerzeichen)
        sed -i "s/APP_VERSION.*/APP_VERSION = \"$CLEAN_VERSION\"/" config.py
        
        # version -> Umgebungsvariable
        echo "CLEAN_VERSION=$CLEAN_VERSION" >> $GITHUB_ENV
        echo "Building MediaFixer version: $CLEAN_VERSION"

    - name: Build with PyInstaller
      shell: bash
      run: |
        
        pyinstaller --noconsole ${{ matrix.pyinstaller_mode }} --name "${{ matrix.artifact_name }}-${{ env.CLEAN_VERSION }}" \
        --add-data "locales${{ matrix.sep }}locales" \
        --add-data "audio_flags.json${{ matrix.sep }}." \
        --add-data "rime.json${{ matrix.sep }}." \
        --collect-binaries pymediainfo \
        main.py

    - name: Zip Windows Folder
      if: matrix.os == 'windows-latest'
      shell: pwsh
      run: |
        # versionierte zip erstellen
        Compress-Archive -Path "dist/${{ matrix.artifact_name }}-${{ env.CLEAN_VERSION }}" -DestinationPath "dist/${{ matrix.artifact_name }}-${{ env.CLEAN_VERSION }}.zip" -Force

    - name: Upload Release Assets
      uses: softprops/action-gh-release@v2
      with:
        files: |
          dist/${{ matrix.artifact_name }}-${{ env.CLEAN_VERSION }}
          dist/${{ matrix.artifact_name }}-${{ env.CLEAN_VERSION }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}